### ISSUE TITLE
Toggle button not working

### ISSUE THREAD

**Issue by sirben99** [segabl/pd2-player-randomizer#6]
Hey!

I dont know if you maintain this mod anymore, but the button to disable/enable the mod doesent work. If i want to toggle the mod on or off in heist ready screen, i have to do it manually (Horrible right?). All jokes aside it would be nice that this gets fixed. If this is intented, please explain me how it should work!
I also posted a message on the mods ModWorkshop page just incase, since i dont know where ur being then most active.

Cheers!

Ben

**Comment by segabl** [comment]
You mean the keybind or the menu option?

**Comment by sirben99** [comment]
> You mean the keybind or the menu option?

I think the keybind it self. Menu option to disable/enable works without problems. Also sorry for the late responce

**Comment by segabl** [comment]
Should be fixed in 5b8fac2872fa06793263c86fe23c18481662ccde
